version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  deploy:
    machine: true
    steps:
      - run:
          name: Deploy Over SSH
          shell: /bin/bash
          command: |
            echo 'Performing connection...' 
            ssh $SSH_USER@$SSH_HOST "cd /var/www/neutrino-web && git reset --hard && 
            git checkout beta && git pull origin beta && echo 'Started deploying...' && bash deploy.sh --simple"
workflows:
    build-and-test:
      jobs:
        - deploy
        - build-and-test:
            requires:
              - deploy
            filters:
                branches:
                    only:
                        - beta
                        - circle-ci-configure